backend:
  name: git-gateway
  branch: master
media_folder: content/images
collections:
  - label: "Pages"
    name: "pages"
    media_folder: "./images"
    public_folder: "images"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - label: "Image"
            name: image
            widget: image
          - label: "Heading"
            name: heading
            widget: string
          - label: "Subheading"
            name: subheading
            widget: string
